var json = {
    "match1": {
        "gDate": ["Game Date: ", ],
        "gTime": ["Game Time: ", ],
        "gField": ["Game Field: ", ],
        "gAge": ["Age Group: ", ],
        "gGender": ["Gender: ", ],
        "gComp": ["Is Competetive: ", ],
        "gHome": ["Home Team: ", ],
        "gAway": ["Away Team: ", ],
        "gComments": ["Comments: ", ],
        "ref": ["Referee: ", ],
        "refGrd": ["Grade: ", ],
        "refYrs": ["Years Reffing: ", ],
        "refEml": ["E-Mail: ", ],
        "ar1": ["AR 1: ", ],
        "ar1Grd": ["Grade: ", ],
        "ar1Yrs": ["Years Reffing: ", ],
        "ar1Eml": ["E-Mail: ", ],
        "ar2": ["AR 2: ", ],
        "ar2Grd": ["Grade: ", ],
        "ar2Yrs": ["Years Reffing: ", ],
        "ar2Eml": ["E-Mail: ", ]
    },
    "match2": {
        "gDate": ["Game Date: ", ],
        "gTime": ["Game Time: ", ],
        "gField": ["Game Field: ", ],
        "gAge": ["Age Group: ", ],
        "gGender": ["Gender: ", ],
        "gComp": ["Is Competetive: ", ],
        "gHome": ["Home Team: ", ],
        "gAway": ["Away Team: ", ],
        "gComments": ["Comments: ", ],
        "ref": ["Referee: ", ],
        "refGrd": ["Grade: ", ],
        "refYrs": ["Years Reffing: ", ],
        "refEml": ["E-Mail: ", ],
        "ar1": ["AR 1: ", ],
        "ar1Grd": ["Grade: ", ],
        "ar1Yrs": ["Years Reffing: ", ],
        "ar1Eml": ["E-Mail: ", ],
        "ar2": ["AR 2: ", ],
        "ar2Grd": ["Grade: ", ],
        "ar2Yrs": ["Years Reffing: ", ],
        "ar2Eml": ["E-Mail: ", ]
    },
    "match3": {
        "gDate": ["Game Date: ", ],
        "gTime": ["Game Time: ", ],
        "gField": ["Game Field: ", ],
        "gAge": ["Age Group: ", ],
        "gGender": ["Gender: ", ],
        "gComp": ["Is Competetive: ", ],
        "gHome": ["Home Team: ", ],
        "gAway": ["Away Team: ", ],
        "gComments": ["Comments: ", ],
        "ref": ["Referee: ", ],
        "refGrd": ["Grade: ", ],
        "refYrs": ["Years Reffing: ", ],
        "refEml": ["E-Mail: ", ],
        "ar1": ["AR 1: ", ],
        "ar1Grd": ["Grade: ", ],
        "ar1Yrs": ["Years Reffing: ", ],
        "ar1Eml": ["E-Mail: ", ],
        "ar2": ["AR 2: ", ],
        "ar2Grd": ["Grade: ", ],
        "ar2Yrs": ["Years Reffing: ", ],
        "ar2Eml": ["E-Mail: ", ]  
    }
};